name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4.1.0
      with:
        python-version: 3.9.2
    - name: Install poetry ${{ matrix.poetry-version }}
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install poetry==1.1.5 
    - name: Install dependencies for project
      run: poetry install --quiet
    - name: Lint with flake8
      run: poetry run flake8 -q
    - name: Run pytest for tests o coverage in project
      run: |
        poetry run pytest --cov=./source/atividade/POO
        poetry run codecov
